### ISSUE TITLE
About Gen_LaneNet

### ISSUE THREAD

**Issue by CompliceU** [once-3dlanes/once_3dlanes_benchmark#3]
@once-3dlanes Hello, I saw from your paper in the method of comparing Gen_LaneNet method, which requires the use of camera height and pitch angle, I don't know how you trained the experiment，thank you very much

**Comment by once-3dlanes** [comment]
Thanks for the question. 
These extrinsics are provided internally by Huawei, we are not sure whether it will violate the terms of use of the ONCE dataset, so we won't make them public for the time being.

**Comment by CompliceU** [comment]
@once-3dlanes Thank you very much for your reply, can you tell me about the test results on Gen_LaneNet using the camera height and pitch angle?

**Comment by once-3dlanes** [comment]
The results are shown in Table 3 of our paper, you can refer to the paper for details.
