### ISSUE TITLE
Completed depth map & Binary 2D segmentation map

### ISSUE THREAD

**Issue by voldemortX** [once-3dlanes/once_3dlanes_benchmark#4]
Will these be provided also? For training the proposed SALAD method. Especially the seg map, I don't think I can generate the same thing given only 3D points?

I can understand if the code can't be made public (or can't in the near future), but I need these auxiliary labels to reproduce the results by myself soon. https://github.com/once-3dlanes/once_3dlanes_benchmark/issues/1#issuecomment-1113542029

Could you guys help with that and kindly release the annotations? cc @nick112358 @once-3dlanes

**Comment by once-3dlanes** [comment]
1. The depth map and binary 2D segmentation map are produced during training, which means no auxiliary labels can be provided.
2. We have the plan for open source the code of our method in the coming future, including how we produce these labels during the training process. 
3. We have also described in our paper how we produce the depth maps using depth completion. You can refer to our paper and our reference (In defense of classical image processing: Fast depth completion on the cpu) for more details.
