### ISSUE TITLE
question about your metric?

### ISSUE THREAD

**Issue by cedricgsh** [once-3dlanes/once_3dlanes_benchmark#5]
This is a great work in 3d lane detection . I have a question about your evaluation metric. In the `readme`, you provide pred json format, it seem that the `lanes` is only attribute in pred json. However, in your [code](https://github.com/once-3dlanes/once_3dlanes_benchmark/blob/master/evaluation/eval_utils.py#L219), the pred json still requires `points` and `score`.  So I cannot directly apply your evaluation code, how can I fix the problem? I am looking forward to your help.
@nick112358 @Ivanyan0516 @once-3dlanes

**Comment by Aguin** [comment]
Hi, @once-3dlanes 
I think the output format [here](https://github.com/once-3dlanes/once_3dlanes_benchmark#data-preparation) is incompatible with the evaluation code.

```
{
  "lanes":[
    # One lane 
    [ 
      # The [x, y, z] coordinates of key points in the lane are listed as follows.
      [-2.475, 1.871, 31.082],
      [-2.547, 1.854, 28.394],        
      ...
    ]
    # Other lanes
    ...
    ]
}
```
maybe it could be corrected as this
```
{
  "lanes":[
    # One lane 
    {
      "points": [ 
        # The [x, y, z] coordinates of key points in the lane are listed as follows.
        [-2.475, 1.871, 31.082],
        [-2.547, 1.854, 28.394],        
        ...
      ],
      "score": 0.7954080700874329,
    },
    # Other lanes
    ...
  ]
}
```

**Comment by once-3dlanes** [comment]
Thanks for the question, the value of 'score' has no impact on the metric, you can fill in any number as the value, we add it because it makes it easy for tuning parameters.

**Comment by cedricgsh** [comment]
@Aguin Have you try correct formats that you mentioned?

**Comment by Aguin** [comment]
@cedricgsh yes, this works for me
