### ISSUE TITLE
Empty json files in the training dataset

### ISSUE THREAD

**Issue by Aguin** [once-3dlanes/once_3dlanes_benchmark#6]
Hi, @once-3dlanes 
I found some empty json files in the training dataset, could you please fix them or we should just drop these files?
```
ONCE_3DLanes/train/000187/cam01/1618776914500.json
ONCE_3DLanes/train/000473/cam01/1619801784499.json
ONCE_3DLanes/train/000528/cam01/1619977228700.json
ONCE_3DLanes/train/000567/cam01/1620681012299.json
```

**Comment by once-3dlanes** [comment]
Empty files mean that there is no lane in the current scene, there is no need to drop these files.
