### ISSUE TITLE
Path error in file parser

### ISSUE THREAD

**Issue by Aguin** [once-3dlanes/once_3dlanes_benchmark#7]
Hi, @once-3dlanes 
As mentioned [here](https://github.com/once-3dlanes/once_3dlanes_benchmark#data-preparation), the dataset & prediction should be organized as `pred_dir/sequence/cam01/frame.json`, I think `cam01` should be inserted  into the path in the file parser.
https://github.com/once-3dlanes/once_3dlanes_benchmark/blob/master/evaluation/eval_utils.py#L56

**Comment by once-3dlanes** [comment]
thanks for the question, we have modified the code.
